package Footlocker


//https://www.footlocker.com/apigate/release-calendar
import (
	"fmt"
	"math/rand"
	"strconv"
	"time"
	"github.com/brianvoe/gofakeit/v6"
	"github.com/go-resty/resty/v2"
	"strings"
	struc "main/testFolder"

)


type LoginData struct {
	Password string `json:"password"`
	Email string `json:"uid"`
}
type AutoGenerated struct {
	FlxTcVersion         string `json:"flxTcVersion"`
	Birthday             string `json:"birthday"`
	BannerEmailOptIn     bool   `json:"bannerEmailOptIn"`
	PhoneNumber          string `json:"phoneNumber"`
	UID                  string `json:"uid"`
	PreferredLanguage    string `json:"preferredLanguage"`
	FirstName            string `json:"firstName"`
	LoyaltyStatus        bool   `json:"loyaltyStatus"`
	Password             string `json:"password"`
	LastName             string `json:"lastName"`
	PostalCode           string `json:"postalCode"`
	LoyaltyFlxEmailOptIn bool   `json:"loyaltyFlxEmailOptIn"`
	GRecaptchaResponse   string `json:"g-recaptcha-response"`
}
//func Gen(email string, ch chan bool, wg *sync.WaitGroup, taskNumber int, proxy string, password string, zipcode string, c1.ReturnData chan map[string]string) {
func Gen(config interface{}, necessary interface{}){
	c1, _ := necessary.(struc.Necessary)
	c, _ := config.(struc.SiteStructure)
	defer c1.WaitGroup.Done()
	c1.CH <- true
	
	email := c1.Email
	proxy := c1.Proxy
	taskNumber := c1.TaskNumber
	zipcode := c.Store
	password := "Hoglund_6"

	stringTask := strconv.Itoa(taskNumber)
	fmt.Println("Starting Task: " + stringTask)
	a := time.Now().UnixNano() / int64(time.Millisecond)
	requestID := strings.ToUpper(GenRandom(8)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(12))
	deviceID := strings.ToUpper(GenRandom(8)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(12))
	trace := GenRandom(16)
	client := resty.New()
	client.SetHeader("Host", "www.footlocker.com")
	client.SetHeader("tracestate", "@nr=0-2-2684125-826625362-" + trace + "--0--" + strconv.FormatInt(int64(a), 10))
	client.SetHeader("Accept", "application/json")
	client.SetHeader("X-FL-APP-VERSION", "5.4.0")
	client.SetHeader("X-FLAPI-API-IDENTIFIER", "921B2b33cAfba5WWcb0bc32d5ix89c6b0f614")
	client.SetHeader("newrelic", GenerateRelic())
	client.SetHeader("X-FL-DEVICE-ID", deviceID)
	client.SetHeader("Accept-Language", "en-us")
	client.SetHeader("X-API-KEY", "m38t5V0ZmfTsRpKIiQlszub1Tx4FbnGG")
	client.SetHeader("traceparent", "00-" + GenRandom(32) + "-" + trace + "-00")
	client.SetHeader("User-Agent", "FootLocker/CFNetwork/Darwin")
	client.SetHeader("X-API-COUNTRY", "US")
	client.SetHeader("X-API-LANG", "en-US")
	client.SetHeader("X-FL-REQUEST-ID", requestID)
	client.SetProxy(proxy)
    resp, err := client.R().
    Get("https://www.footlocker.com/apigate/v3/session")
    if err != nil || !strings.Contains(resp.String(), "csrfToken"){
    	<- c1.CH
    	c1.ReturnData <- map[string]string{"email": email, "status": "Bad"}
    	return 
    }

    csrf := strings.Split(strings.Split(resp.String(), `{"data":{"csrfToken":"`)[1], "\"")[0]
    sessionID := strings.Split(strings.Split(resp.Header()["Set-Cookie"][0], "JSESSIONID=")[1], ";")[0]
    randName := gofakeit.Name()
    randFirstName := strings.Split(randName, " ")[0]
    randLastName := strings.Split(randName, " ")[1]

    accountDetails := AutoGenerated{
    	FlxTcVersion: "1.0",
    	Birthday: randomBirthday(),
    	BannerEmailOptIn: false,
    	PhoneNumber: phoneNumberGen(),
    	UID: email,
    	PreferredLanguage: "en",
    	FirstName: randFirstName,
    	LoyaltyStatus: true,
    	Password: password,
    	LastName: randLastName,
    	PostalCode: zipcode,
    	LoyaltyFlxEmailOptIn: false,
    	GRecaptchaResponse: randomCaptcha(),
    }
    resp2, _ := client.R().
    SetHeader("X-NewRelic-ID", "VgAPVVdRDRAIVldUBQQEUFY=").
	SetHeader("X-FLAPI-SESSION-ID", sessionID).
	SetHeader("X-CSRF-TOKEN", csrf).
	SetHeader("X-FL-REQUEST-ID", strings.ToUpper(GenRandom(8)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(4)) + "-" + strings.ToUpper(GenRandom(12))).
	SetHeader("Content-Type", "application/json").
    SetBody(accountDetails).
    Post("https://www.footlocker.com/apigate/v3/users")
    fmt.Println(resp2.String())
    if resp2.StatusCode() == 201 {
    	c1.ReturnData <- map[string]string{"email": email, "status": "Good"}

    } else {

    	if strings.Contains(resp2.String(), "User already has an account") {
    		fmt.Println("Duplicate Account")
    	} else if strings.Contains(resp2.String(), "geo") {
    		fmt.Println("Proxy Ban")
    	}

    	c1.ReturnData <- map[string]string{"email": email, "status": "Bad"}

    }
    <- c1.CH

    

}

func randomBirthday() string{
	rand.Seed(time.Now().UnixNano())
	month := []string{"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"}
	day := []string{"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}
	randomYear := 1980 + rand.Intn(20)
	return string(month[rand.Intn(len(month))]) + `\\/` + string(day[rand.Intn(len(day))]) + `\\/` + strconv.Itoa(randomYear)
}

func phoneNumberGen() string{
	rand.Seed(time.Now().UnixNano())
	areaCode := []string{"646", "929", "917", "718", "347"}
	randomInt := rand.Intn(9999999 - 1111111) + 1111111
	return string(areaCode[rand.Intn(len(areaCode))]) + strconv.Itoa(randomInt)
}

func randomZipcode() string{
	rand.Seed(time.Now().UnixNano())
	randomZip := rand.Intn(99999 - 11111) + 11111
	return strconv.Itoa(randomZip)
}

func randomCaptcha() string{
	rand.Seed(time.Now().UnixNano())
	a := "24C22Pt4hYTpo6ssRCBQzdR6pUT-IyvsXyRc8YvyVaDpVI5NlPy7WlXQtqifvvSChDRydf3TbdXbzM8UNdBlw66LWop_TdzbynVRGeAJRcvDcu-uuOjXR7U6cMzKdl6q9PK2CjTgCOSW02Lk2NOq3lVPN6luI0WJ2kBDMFIP-FW6FajBzs2hbAke7Gi8NztMOgzdxFX-wLsq7FPH8_9JAGfpJblh971NKyCpWLukva17c0X38JVRaXtDeuG0h7EVXnf374PbInkKCKgEyx1gVBgd0lLbwWzDw4NkuBu8dJ3DWeJYhObmJWw6E2gfL64LOLtBnZjpylrQ4YiVFAHfMGFUeH_wUUQL_M7DGaSSLmSyoM_5nrI90mw4OomizVKf1cd5MhAfcu40fIdiqSEGGjIPgeIPYQ-ECZ8AGNiI9UwQy94PqqvVPMFGQy5CPYVEoNOIURz"
	b := "03AGdBq"
	for i := 0; i < len(a); i++ {
		b += string(a[rand.Intn(len(a))])
	}
	return b
}